import SwiftUI

struct BooksView: View { @EnvironmentObject private var store: LedgerStore; @State private var search = ""; @State private var newBook = false
    var body: some View { List { ForEach(store.books.filter { search.isEmpty || $0.name.localizedCaseInsensitiveContains(search) }.sorted { $0.isPinned && !$1.isPinned }) { book in NavigationLink { BookDetailView(book: book) } label: { BookRow(book: book) } }.onDelete { offsets in store.books.remove(atOffsets: offsets); store.save() } }.overlay { if store.books.isEmpty { EmptyState(title: "还没有账本", systemImage: "books.vertical") } }.navigationTitle("账本").searchable(text: $search, prompt: "搜索账本").toolbar { Button { newBook = true } label: { Image(systemName: "plus") } }.sheet(isPresented: $newBook) { BookEditor() } }
}
struct BookRow: View { @EnvironmentObject private var store: LedgerStore; let book: LedgerBook
    var body: some View { let items = store.transactions.filter { $0.bookIDs.contains(book.id) }; HStack { Image(systemName: book.icon).frame(width: 44, height: 44).background(book.color.opacity(0.15), in: RoundedRectangle(cornerRadius: 12)).foregroundStyle(book.color); VStack(alignment: .leading) { HStack { Text(book.name).font(.headline); if book.isPinned { Image(systemName: "pin.fill").font(.caption).foregroundStyle(.orange) } }; Text("\(items.count) 笔 · 支出 \(items.filter { $0.kind == .expense }.reduce(0) { $0 + $1.amount }.currency)").font(.caption).foregroundStyle(.secondary) }; Spacer(); if book.budgetLimit > 0 { Text("预算 \(book.budgetLimit.currency)").font(.caption2).foregroundStyle(.secondary) } } }
}
struct BookDetailView: View { @EnvironmentObject private var store: LedgerStore; let book: LedgerBook; @State private var editor = false
    var body: some View { let items = store.transactions.filter { $0.bookIDs.contains(book.id) }; List { Section { BookRow(book: book); if book.participants.count > 1 { Label("参与人：\(book.participants.joined(separator: "、"))", systemImage: "person.2") } } header: { Text("账本摘要") }; Section("关联流水") { ForEach(items) { TransactionRow(transaction: $0) } } }.navigationTitle(book.name).toolbar { Button("编辑") { editor = true } }.sheet(isPresented: $editor) { BookEditor(existing: book) } }
}
struct BookEditor: View { @EnvironmentObject private var store: LedgerStore; @Environment(\.dismiss) private var dismiss; let existing: LedgerBook?; @State private var book: LedgerBook; @State private var participant = ""
    init(existing: LedgerBook? = nil) { self.existing = existing; _book = State(initialValue: existing ?? LedgerBook(name: "")) }
    var body: some View { NavigationStack { Form { Section("基础") { TextField("账本名称", text: $book.name); TextField("图标 SF Symbol", text: $book.icon); ColorPicker("颜色", selection: Binding(get: { book.color }, set: { book.colorHex = $0.hexString })); DatePicker("开始", selection: $book.startDate, displayedComponents: .date); DatePicker("结束", selection: $book.endDate, displayedComponents: .date); Toggle("置顶", isOn: $book.isPinned) }; Section("预算与自动归集") { TextField("账本预算", value: $book.budgetLimit, format: .number); Toggle("启用自动归集", isOn: $book.autoCollectEnabled); if book.autoCollectEnabled { ForEach(store.categories.filter { $0.kind == .expense }) { category in Toggle(category.name, isOn: Binding(get: { book.autoCollectCategoryIDs.contains(category.id) }, set: { selected in if selected { book.autoCollectCategoryIDs.append(category.id) } else { book.autoCollectCategoryIDs.removeAll { $0 == category.id } } })) } } }; Section("多人分账") { ForEach(book.participants, id: \.self) { Text($0) }.onDelete { book.participants.remove(atOffsets: $0) }; HStack { TextField("参与人名称", text: $participant); Button("添加") { guard !participant.isEmpty else { return }; book.participants.append(participant); participant = "" } } } }.navigationTitle(existing == nil ? "新建账本" : "编辑账本").toolbar { ToolbarItem(placement: .confirmationAction) { Button("保存") { if let index = store.books.firstIndex(where: { $0.id == book.id }) { store.books[index] = book } else { store.books.append(book) }; store.save(); dismiss() }.disabled(book.name.isEmpty || book.endDate < book.startDate) }; ToolbarItem(placement: .cancellationAction) { Button("取消") { dismiss() } } } } }
}
struct MoreView: View { var body: some View { List { Section("管理") { NavigationLink("预算", destination: BudgetsView()); NavigationLink("分类", destination: CategoriesView()); NavigationLink("识图记账", destination: OCRImportView()) }; Section("偏好") { NavigationLink("设置", destination: SettingsView()) } }.navigationTitle("更多") } }
struct CategoriesView: View { @EnvironmentObject private var store: LedgerStore; @State private var editor: LedgerCategory?
    var body: some View { List { ForEach(FlowType.allCases) { kind in Section(kind.title) { ForEach(store.categories.filter { $0.kind == kind && $0.parentID == nil }) { parent in VStack(alignment: .leading, spacing: 10) { Button { editor = parent } label: { Label(parent.name, systemImage: parent.icon).foregroundStyle(parent.color) }.buttonStyle(.plain); ForEach(store.categories.filter { $0.parentID == parent.id }) { child in Button { editor = child } label: { Label(child.name, systemImage: child.icon).padding(.leading, 24).foregroundStyle(child.color) }.buttonStyle(.plain) } } }.onDelete { indexes in let parents = store.categories.filter { $0.kind == kind && $0.parentID == nil }; for index in indexes { store.categories.removeAll { $0.id == parents[index].id || $0.parentID == parents[index].id } }; store.save() } } } }.navigationTitle("分类").toolbar { Button { editor = LedgerCategory(name: "", kind: .expense, icon: "tag.fill", colorHex: "F59E0B", parentID: nil) } label: { Image(systemName: "plus") } }.sheet(item: $editor) { item in CategoryEditor(category: item) } }
}

struct CategoryEditor: View { @EnvironmentObject private var store: LedgerStore; @Environment(\.dismiss) private var dismiss; let original: LedgerCategory; @State private var category: LedgerCategory
    private let icons = ["tag.fill", "fork.knife", "cup.and.saucer.fill", "car.fill", "bag.fill", "house.fill", "gamecontroller.fill", "cross.case.fill", "banknote.fill"]
    init(category: LedgerCategory) { original = category; _category = State(initialValue: category) }
    var body: some View { NavigationStack { Form { Picker("收支类型", selection: $category.kind) { ForEach(FlowType.allCases) { Text($0.title).tag($0) } }; TextField("名称", text: $category.name); Picker("父分类", selection: $category.parentID) { Text("无（一级分类）").tag(UUID?.none); ForEach(store.categories.filter { $0.kind == category.kind && $0.parentID == nil && $0.id != category.id }) { Text($0.name).tag(Optional($0.id)) } }; Picker("图标", selection: $category.icon) { ForEach(icons, id: \.self) { Label($0, systemImage: $0).tag($0) } }; ColorPicker("颜色", selection: Binding(get: { category.color }, set: { category.colorHex = $0.hexString })) }.navigationTitle(original.name.isEmpty ? "新建分类" : "编辑分类").toolbar { ToolbarItem(placement: .confirmationAction) { Button("保存") { if original.name.isEmpty { store.categories.append(category) } else if let index = store.categories.firstIndex(where: { $0.id == category.id }) { store.categories[index] = category }; store.save(); dismiss() }.disabled(category.name.isEmpty) }; ToolbarItem(placement: .cancellationAction) { Button("取消") { dismiss() } } } } }
}
struct BudgetsView: View { @EnvironmentObject private var store: LedgerStore; @State private var showAdd = false
    var body: some View { List { ForEach(store.budgets) { budget in let spent = store.expense(in: DashboardRange.month.interval(), categoryID: budget.categoryID); VStack(alignment: .leading) { HStack { Text(budget.name).font(.headline); Spacer(); Text("\(spent.currency) / \(budget.limitAmount.currency)") }; ProgressView(value: min(spent / budget.limitAmount, 1)); Text(budget.period.title).font(.caption).foregroundStyle(.secondary) } }.onDelete { store.budgets.remove(atOffsets: $0); store.save() } }.navigationTitle("预算").toolbar { Button { showAdd = true } label: { Image(systemName: "plus") } }.sheet(isPresented: $showAdd) { BudgetEditor() } }
}
struct BudgetEditor: View { @EnvironmentObject private var store: LedgerStore; @Environment(\.dismiss) private var dismiss; @State private var name = ""; @State private var amount = 0.0; @State private var categoryID: UUID?
    var body: some View { NavigationStack { Form { TextField("预算名称", text: $name); TextField("金额", value: $amount, format: .number); Picker("分类范围", selection: $categoryID) { Text("全部支出").tag(UUID?.none); ForEach(store.categories.filter { $0.kind == .expense && $0.parentID == nil }) { Text($0.name).tag(Optional($0.id)) } } }.navigationTitle("新建预算").toolbar { ToolbarItem(placement: .confirmationAction) { Button("保存") { store.budgets.append(Budget(name: name, limitAmount: amount, categoryID: categoryID)); store.save(); dismiss() }.disabled(name.isEmpty || amount <= 0) } } } }
