import SwiftUI

struct CreateTransactionView: View {
    @EnvironmentObject private var store: LedgerStore; @Environment(\.dismiss) private var dismiss; var existing: LedgerTransaction?
    @State private var transaction: LedgerTransaction; @State private var installmentEnabled = false; @State private var selectedBooks: Set<UUID> = []
    init(existing: LedgerTransaction? = nil) { self.existing = existing; _transaction = State(initialValue: existing ?? LedgerTransaction(title: "", amount: 0, kind: .expense)); _selectedBooks = State(initialValue: Set(existing?.bookIDs ?? [])); _installmentEnabled = State(initialValue: (existing?.installmentMonths ?? 1) > 1) }
    var body: some View { Form { Section("基础信息") { Picker("类型", selection: $transaction.kind) { ForEach(FlowType.allCases) { Text($0.title).tag($0) } }.pickerStyle(.segmented); TextField("标题", text: $transaction.title); TextField("金额", value: $transaction.amount, format: .number.precision(.fractionLength(2))).keyboardType(.decimalPad); TextField("支付渠道", text: $transaction.paymentMethod); DatePicker("时间", selection: $transaction.happenedAt) }
        Section("分类与账本") { Picker("分类", selection: $transaction.categoryID) { Text("未分类").tag(UUID?.none); ForEach(store.categories.filter { $0.kind == transaction.kind }) { category in Text(category.parentID == nil ? category.name : "  └ \(category.name)").tag(Optional(category.id)) } }; if store.recommendBooks && !store.automaticBookIDs(for: transaction).isEmpty { Text("推荐归入：\(store.books.filter { store.automaticBookIDs(for: transaction).contains($0.id) }.map(\.name).joined(separator: "、"))").font(.caption).foregroundStyle(.blue) }; NavigationLink("账本归属（可多选）") { List(store.books) { book in Button { if selectedBooks.contains(book.id) { selectedBooks.remove(book.id) } else { selectedBooks.insert(book.id) } } label: { HStack { Label(book.name, systemImage: book.icon); Spacer(); if selectedBooks.contains(book.id) { Image(systemName: "checkmark") } } }.foregroundStyle(.primary) } }
        Section("分期与分账") { Toggle("启用分期", isOn: $installmentEnabled); if installmentEnabled { Stepper("分期月数：\(transaction.installmentMonths)", value: $transaction.installmentMonths, in: 2...36) }; if let book = store.books.first(where: { selectedBooks.contains($0.id) && $0.participants.count > 1 }) { Picker("付款人", selection: $transaction.paidBy) { Text("请选择").tag(""); ForEach(book.participants, id: \.self) { Text($0).tag($0) } }; ForEach(book.participants, id: \.self) { participant in Toggle("分给 \(participant)", isOn: Binding(get: { transaction.splitParticipants.contains(participant) }, set: { selected in if selected { transaction.splitParticipants.append(participant) } else { transaction.splitParticipants.removeAll { $0 == participant } } })) } } }
        Section("高级") { TextField("商户", text: $transaction.merchant); TextField("备注", text: $transaction.note); TextField("原价", value: $transaction.originalAmount, format: .number); TextField("优惠", value: $transaction.discountAmount, format: .number) }
    }.navigationTitle(existing == nil ? "新增流水" : "编辑流水").toolbar { ToolbarItem(placement: .confirmationAction) { Button("保存") { save() }.disabled(transaction.amount <= 0 || transaction.title.trimmingCharacters(in: .whitespaces).isEmpty) }; ToolbarItem(placement: .cancellationAction) { if existing != nil { Button("取消") { dismiss() } } } } }
    private func save() { transaction.bookIDs = Array(selectedBooks); if transaction.bookIDs.isEmpty && !store.recommendBooks { transaction.bookIDs = store.automaticBookIDs(for: transaction) }; if let book = store.books.first(where: { selectedBooks.contains($0.id) && $0.participants.count > 1 }), (transaction.paidBy.isEmpty || transaction.splitParticipants.isEmpty) { return }; if installmentEnabled && transaction.installmentMonths > 1 { let group = UUID(); let monthly = transaction.amount / Double(transaction.installmentMonths); for index in 0..<transaction.installmentMonths { var item = transaction; item.id = UUID(); item.amount = monthly; item.installmentGroupID = group; item.installmentIndex = index + 1; item.happenedAt = Calendar.current.date(byAdding: .month, value: index, to: transaction.happenedAt)!; store.add(item) } } else if existing == nil { store.add(transaction) } else { store.update(transaction) }; dismiss() }
}
