import SwiftUI
import PhotosUI
import Vision

struct OCRImportView: View { @EnvironmentObject private var store: LedgerStore; @State private var imageItem: PhotosPickerItem?; @State private var results: [OCRImportResult] = []; @State private var isRecognizing = false; @State private var selected = Set<UUID>(); @State private var error: String?
    var body: some View { List { Section { PhotosPicker(selection: $imageItem, matching: .images) { Label("选择账单截图", systemImage: "photo.on.rectangle") }.onChange(of: imageItem) { _, item in Task { await recognize(item) } }; if isRecognizing { HStack { ProgressView(); Text("正在识别文字…") } } } header: { Text("识图记账") } footer: { Text("识别结果仅为草稿，确认后才会写入本地账本。") }
        if !results.isEmpty { Section("识别结果") { ForEach(results) { result in Button { if selected.contains(result.id) { selected.remove(result.id) } else { selected.insert(result.id) } } label: { HStack { VStack(alignment: .leading) { Text(result.title); Text("\(result.amount.currency) · \(Int(result.confidence * 100))% 置信度").font(.caption).foregroundStyle(.secondary) }; Spacer(); Image(systemName: selected.contains(result.id) ? "checkmark.circle.fill" : "circle").foregroundStyle(.blue) } }.foregroundStyle(.primary) }; Button("确认入账（\(selected.count) 笔）") { saveSelected() }.disabled(selected.isEmpty) } } }.navigationTitle("识图记账").alert("识别失败", isPresented: Binding(get: { error != nil }, set: { if !$0 { error = nil } })) { Button("好", role: .cancel) {} } message: { Text(error ?? "") } }
    private func recognize(_ item: PhotosPickerItem?) async { guard let data = try? await item?.loadTransferable(type: Data.self), let image = UIImage(data: data) else { return }; isRecognizing = true; defer { isRecognizing = false }; do { let text = try await OCRService.recognize(image: image); results = ReceiptParser().parseMultiple(rawText: text); if results.isEmpty { results = [ReceiptParser().parse(rawText: text)] }; selected = Set(results.map(\.id)) } catch { self.error = error.localizedDescription } }
    private func saveSelected() { for result in results where selected.contains(result.id) { let category = store.categories.first { $0.name == result.categoryPath.last && $0.kind == result.kind }; store.add(LedgerTransaction(title: result.title, amount: result.amount, kind: result.kind, happenedAt: result.happenedAt, merchant: result.merchant, paymentMethod: result.paymentMethod, source: "ocr", categoryID: category?.id, originalAmount: result.originalAmount, discountAmount: result.discountAmount)) }; results = []; selected = [] }
}

enum OCRService { static func recognize(image: UIImage) async throws -> String { try await withCheckedThrowingContinuation { continuation in let request = VNRecognizeTextRequest { request, error in if let error { continuation.resume(throwing: error); return }; let lines = (request.results as? [VNRecognizedTextObservation])?.compactMap { $0.topCandidates(1).first?.string } ?? []; continuation.resume(returning: lines.joined(separator: "\n")) }; request.recognitionLanguages = ["zh-Hans", "en-US"]; request.usesLanguageCorrection = true; DispatchQueue.global(qos: .userInitiated).async { do { try VNImageRequestHandler(cgImage: image.cgImage!, options: [:]).perform([request]) } catch { continuation.resume(throwing: error) } } } } }

struct ReceiptParser {
    func parse(rawText: String) -> OCRImportResult { let lines = normalized(rawText); let detail = fieldMap(lines); let amount = findAmount(lines) ?? 0; let kind: FlowType = lines.joined(separator: " ").contains("收款") && !lines.joined(separator: " ").contains("付款") ? .income : .expense; let merchant = detail["商户全名"] ?? detail["收款方"] ?? detail["交易对方"] ?? lines.first(where: isTitle) ?? "待确认商户"; let payment = detail["付款方式"] ?? detail["支付方式"] ?? paymentMethod(lines) ?? "待确认"; let date = findDate(lines) ?? Date(); let path = categoryPath(for: merchant, kind: kind); return OCRImportResult(amount: amount, kind: kind, merchant: merchant, title: merchant, paymentMethod: payment, happenedAt: date, categoryPath: path, confidence: confidence(amount: amount, merchant: merchant, payment: payment), rawLines: lines, originalAmount: extract(lines, keyword: "原价"), discountAmount: extract(lines, keyword: "优惠")) }
    func parseMultiple(rawText: String) -> [OCRImportResult] { let lines = normalized(rawText); let datePositions = lines.indices.filter { lines[$0].range(of: "^\\d{1,2}月\\d{1,2}日|^\\d{4}-\\d{2}-\\d{2}", options: .regularExpression) != nil }; guard datePositions.count > 1 else { return [] }; return datePositions.enumerated().compactMap { offset, start in let end = offset + 1 < datePositions.count ? datePositions[offset + 1] : lines.count; let section = lines[max(0,start-3)..<end].joined(separator: "\n"); let result = parse(rawText: section); return result.amount > 0 ? result : nil } }
    private func normalized(_ text: String) -> [String] { text.split(whereSeparator: \.isNewline).map { $0.trimmingCharacters(in: .whitespaces).replacingOccurrences(of: "，", with: ".") }.filter { !$0.isEmpty } }
    private func fieldMap(_ lines: [String]) -> [String:String] { let labels = ["支付时间", "付款方式", "支付方式", "商户全名", "收款方", "交易对方", "原价", "优惠"]; var result: [String:String] = [:]; for (index, line) in lines.enumerated() { for label in labels where line.contains(label) { let value = line.replacingOccurrences(of: label, with: "").trimmingCharacters(in: CharacterSet(charactersIn: "：: ")); result[label] = value.isEmpty && index + 1 < lines.count ? lines[index+1] : value } }; return result }
    private func findAmount(_ lines: [String]) -> Double? { let candidates = lines.filter { $0.range(of: "[-+]?[￥¥]?\\s*\\d+(?:\\.\\d{1,2})?", options: .regularExpression) != nil && !$0.contains("原价") && !$0.contains("优惠") }; let source = candidates.first(where: { $0.contains("￥") || $0.contains("¥") }) ?? candidates.first; guard let source else { return nil }; let value = source.replacingOccurrences(of: "[^0-9.]", with: "", options: .regularExpression); return Double(value) }
    private func extract(_ lines: [String], keyword: String) -> Double? { findAmount(lines.filter { $0.contains(keyword) }) }
    private func paymentMethod(_ lines: [String]) -> String? { let values = ["微信零钱", "支付宝余额", "微信支付", "支付宝", "花呗", "云闪付", "信用卡", "银行卡", "现金"]; return values.first { target in lines.contains { $0.contains(target) } } }
    private func findDate(_ lines: [String]) -> Date? { let text = lines.joined(separator: " "); let formatter = DateFormatter(); formatter.locale = Locale(identifier: "zh_CN"); for format in ["yyyy-MM-dd HH:mm:ss", "yyyy-MM-dd HH:mm", "yyyy年M月d日 HH:mm:ss", "yyyy年M月d日 HH:mm"] { formatter.dateFormat = format; if let range = text.range(of: "\\d{4}[-年]\\d{1,2}[-月]\\d{1,2}[日]?\\s+\\d{1,2}:\\d{2}(:\\d{2})?", options: .regularExpression), let date = formatter.date(from: String(text[range])) { return date } }; return nil }
    private func categoryPath(for text: String, kind: FlowType) -> [String] { guard kind == .expense else { return text.contains("工资") ? ["工资"] : [] }; let rules: [(String,[String])] = [("奶茶咖啡",["瑞幸","库迪","星巴克","咖啡","奶茶"]),("日常吃饭",["午饭","晚饭","外卖","快餐"]),("交通",["滴滴","出租车","地铁","公交"]),("旅行",["酒店","旅游"])]; return rules.first { $0.1.contains { text.localizedCaseInsensitiveContains($0) } }.map { $0.0 == "奶茶咖啡" || $0.0 == "日常吃饭" ? ["餐饮", $0.0] : [$0.0] } ?? [] }
    private func isTitle(_ line: String) -> Bool { line.range(of: "[\\p{Han}A-Za-z]", options: .regularExpression) != nil && findAmount([line]) == nil && !line.contains("支付") }
    private func confidence(amount: Double, merchant: String, payment: String) -> Double { min(0.96, 0.45 + (amount > 0 ? 0.25 : 0) + (merchant != "待确认商户" ? 0.15 : 0) + (payment != "待确认" ? 0.1 : 0)) }
}
