import SwiftUI
import PhotosUI

struct SettingsView: View { @EnvironmentObject private var store: LedgerStore; @State private var photo: PhotosPickerItem?; @State private var coordinator: AppleSignInCoordinator?
    var body: some View { Form { Section("外观") { Picker("显示模式", selection: $store.appearance) { ForEach(AppearanceMode.allCases) { Text($0.title).tag($0) } }.onChange(of: store.appearance) { _, _ in store.save() }; PhotosPicker(selection: $photo, matching: .images) { Label(store.backgroundImageData == nil ? "选择背景图片" : "更换背景图片", systemImage: "photo") }.onChange(of: photo) { _, item in Task { store.backgroundImageData = try? await item?.loadTransferable(type: Data.self); store.save() } }; if store.backgroundImageData != nil { Button("清除背景图片", role: .destructive) { store.backgroundImageData = nil; store.save() } } }; Section("Apple 账号") { if let profile = store.appleProfile { LabeledContent("名称", value: profile.fullName); LabeledContent("邮箱", value: profile.email.isEmpty ? "仅 Apple 可见" : profile.email); Text("已绑定于 \(profile.authorizedAt.formatted(date: .numeric, time: .shortened))").font(.caption).foregroundStyle(.secondary); Button("清除本地账号信息", role: .destructive) { store.appleProfile = nil; store.save() } } else { Button("使用 Apple 登录") { let value = AppleSignInCoordinator { result in if case .success(let profile) = result { Task { @MainActor in store.appleProfile = profile; store.save() } } }; coordinator = value; value.start() } } }; Section("iCloud / CloudKit") { Toggle("启用云同步", isOn: $store.cloudSyncEnabled).onChange(of: store.cloudSyncEnabled) { _, enabled in store.save(); Task { await store.refreshCloudStatus() } }; LabeledContent("同步状态", value: store.cloudState.title); Text(store.cloudMessage).font(.caption).foregroundStyle(.secondary); if store.cloudState == .conflict, let cloud = store.cloudConflict { Text("本地：\(store.transactions.count) 笔流水；云端：\(cloud.transactions.count) 笔流水").font(.caption); Button("保留本地版本") { Task { await store.resolveConflict(keepLocal: true) } }; Button("采用 iCloud 版本", role: .destructive) { Task { await store.resolveConflict(keepLocal: false) } } }; if store.cloudSyncEnabled { Button("刷新 iCloud 状态") { Task { await store.refreshCloudStatus() } }; Button("智能同步") { Task { await store.smartSync() } }; Button("仅推送到 iCloud") { Task { await store.pushToCloud() } }; Button("仅从 iCloud 拉取") { Task { await store.pullFromCloud() } } } }; Section("记账") { Toggle("新流水显示账本归属推荐", isOn: $store.recommendBooks).onChange(of: store.recommendBooks) { _, _ in store.save() }; NavigationLink("支付渠道管理") { PaymentMethodsView() } }; Section("开发辅助") { Button("生成一批模拟数据") { store.seed() }.foregroundStyle(.blue) } }.navigationTitle("设置") }
}

struct PaymentMethodsView: View { @EnvironmentObject private var store: LedgerStore; @State private var value = ""
    var body: some View { List { ForEach(store.paymentMethods, id: \.self) { Text($0) }.onDelete { store.paymentMethods.remove(atOffsets: $0); store.save() }; HStack { TextField("新增支付渠道", text: $value); Button("添加") { guard !value.isEmpty else { return }; store.paymentMethods.append(value); value = ""; store.save() } } }.navigationTitle("支付渠道") }
}
