import Foundation
import SwiftUI

@MainActor
final class LedgerStore: ObservableObject {
    @Published var categories: [LedgerCategory] = []; @Published var books: [LedgerBook] = []; @Published var transactions: [LedgerTransaction] = []; @Published var budgets: [Budget] = []
    @Published var appearance: AppearanceMode = .system; @Published var recommendBooks = true; @Published var paymentMethods = ["微信支付", "支付宝", "银行卡", "现金"]
    @Published var backgroundImageData: Data?; @Published var appleProfile: AppleAccountProfile?; @Published var cloudSyncEnabled = false; @Published var cloudState: CloudSyncState = .disabled; @Published var cloudMessage = "本地数据优先"; @Published var cloudConflict: PersistedLedgerSnapshot?
    private let key = "smartLedger.snapshot.v1"
    init() { load(); loadPreferences() }
    var preferredColorScheme: ColorScheme? { appearance == .system ? nil : (appearance == .dark ? .dark : .light) }
    func save() { let value = snapshot; if let data = try? JSONEncoder().encode(value) { UserDefaults.standard.set(data, forKey: key) }; savePreferences() }
    var snapshot: PersistedLedgerSnapshot { PersistedLedgerSnapshot(categories: categories, books: books, transactions: transactions, budgets: budgets, updatedAt: Date()) }
    func apply(_ value: PersistedLedgerSnapshot) { categories = value.categories; books = value.books; transactions = value.transactions; budgets = value.budgets; save() }
    func load() { guard let data = UserDefaults.standard.data(forKey: key), let value = try? JSONDecoder().decode(PersistedLedgerSnapshot.self, from: data) else { seed(); return }; categories = value.categories; books = value.books; transactions = value.transactions; budgets = value.budgets }
    func add(_ transaction: LedgerTransaction) { transactions.append(transaction); save() }
    func update(_ transaction: LedgerTransaction) { guard let index = transactions.firstIndex(where: { $0.id == transaction.id }) else { return }; transactions[index] = transaction; save() }
    func delete(_ transaction: LedgerTransaction) { transactions.removeAll { $0.id == transaction.id }; save() }
    func category(_ id: UUID?) -> LedgerCategory? { categories.first { $0.id == id } }
    func books(for transaction: LedgerTransaction) -> [LedgerBook] { books.filter { transaction.bookIDs.contains($0.id) } }
    func categoryFamily(for category: LedgerCategory) -> Set<UUID> { Set(categories.filter { $0.id == category.id || $0.parentID == category.id }.map(\.id)) }
    func automaticBookIDs(for transaction: LedgerTransaction) -> [UUID] { books.filter { $0.autoCollectEnabled && transaction.happenedAt >= $0.startDate && transaction.happenedAt <= $0.endDate && $0.autoCollectCategoryIDs.contains(transaction.categoryID ?? UUID()) }.map(\.id) }
    func expense(in interval: DateInterval, categoryID: UUID? = nil) -> Double { transactions.filter { $0.kind == .expense && interval.contains($0.happenedAt) && (categoryID == nil || categoryFamily(for: category(categoryID)!).contains($0.categoryID ?? UUID())) }.reduce(0) { $0 + $1.amount } }
    func seed() {
        let food = LedgerCategory(name: "餐饮", kind: .expense, icon: "fork.knife", colorHex: "F59E0B", parentID: nil); let coffee = LedgerCategory(name: "奶茶咖啡", kind: .expense, icon: "cup.and.saucer.fill", colorHex: "F59E0B", parentID: food.id); let transport = LedgerCategory(name: "交通", kind: .expense, icon: "car.fill", colorHex: "3B82F6", parentID: nil); let shopping = LedgerCategory(name: "购物", kind: .expense, icon: "bag.fill", colorHex: "EC4899", parentID: nil); let salary = LedgerCategory(name: "工资", kind: .income, icon: "banknote.fill", colorHex: "22C55E", parentID: nil)
        categories = [food, coffee, transport, shopping, salary]
        let trip = LedgerBook(name: "三亚旅行", icon: "airplane", colorHex: "0EA5E9", startDate: Date().addingTimeInterval(-86400*10), endDate: Date().addingTimeInterval(86400*30), autoCollectEnabled: true, autoCollectCategoryIDs: [food.id, transport.id], budgetLimit: 5000, participants: ["我", "小林"], isPinned: true)
        books = [trip]; budgets = [Budget(name: "本月餐饮", limitAmount: 1500, categoryID: food.id)]
        transactions = [LedgerTransaction(title: "瑞幸咖啡", amount: 18, kind: .expense, happenedAt: Date(), paymentMethod: "微信支付", source: "ocr", categoryID: coffee.id, bookIDs: [trip.id]), LedgerTransaction(title: "滴滴出行", amount: 35.5, kind: .expense, happenedAt: Date().addingTimeInterval(-86400), paymentMethod: "支付宝", categoryID: transport.id, bookIDs: [trip.id]), LedgerTransaction(title: "八月工资", amount: 19000, kind: .income, happenedAt: Date().addingTimeInterval(-86400*3), paymentMethod: "银行卡", categoryID: salary.id)]
        save()
    }
    private func loadPreferences() { let defaults = UserDefaults.standard; appearance = AppearanceMode(rawValue: defaults.string(forKey: "smartLedger.appearance") ?? "system") ?? .system; recommendBooks = defaults.object(forKey: "smartLedger.recommendBooks") as? Bool ?? true; backgroundImageData = defaults.data(forKey: "smartLedger.background"); cloudSyncEnabled = defaults.bool(forKey: "smartLedger.cloudEnabled"); if let data = defaults.data(forKey: "smartLedger.appleProfile") { appleProfile = try? JSONDecoder().decode(AppleAccountProfile.self, from: data) }; cloudState = cloudSyncEnabled ? .idle : .disabled }
    private func savePreferences() { let defaults = UserDefaults.standard; defaults.set(appearance.rawValue, forKey: "smartLedger.appearance"); defaults.set(recommendBooks, forKey: "smartLedger.recommendBooks"); defaults.set(backgroundImageData, forKey: "smartLedger.background"); defaults.set(cloudSyncEnabled, forKey: "smartLedger.cloudEnabled"); if let appleProfile { defaults.set(try? JSONEncoder().encode(appleProfile), forKey: "smartLedger.appleProfile") } else { defaults.removeObject(forKey: "smartLedger.appleProfile") } }
    func refreshCloudStatus() async { guard cloudSyncEnabled else { cloudState = .disabled; return }; do { cloudState = try await CloudLedgerService.accountAvailable() ? .idle : .unavailable; cloudMessage = cloudState == .idle ? "iCloud 可用，等待同步" : "请登录 iCloud 后重试" } catch { cloudState = .failed; cloudMessage = error.localizedDescription } }
    func smartSync() async { guard cloudSyncEnabled else { return }; cloudState = .syncing; cloudMessage = "正在比较本地与 iCloud 数据"; do { guard try await CloudLedgerService.accountAvailable() else { cloudState = .unavailable; cloudMessage = "iCloud 不可用"; return }; guard let cloud = try await CloudLedgerService.fetch() else { try await CloudLedgerService.push(snapshot); cloudState = .success; cloudMessage = "已首次推送到 iCloud"; return }; let local = snapshot; let localData = try JSONEncoder().encode(local); let cloudData = try JSONEncoder().encode(cloud); if abs(cloud.updatedAt.timeIntervalSince(local.updatedAt)) <= 3 && localData != cloudData { cloudConflict = cloud; cloudState = .conflict; cloudMessage = "本地和 iCloud 同时有修改，请选择保留版本" } else if cloud.updatedAt > local.updatedAt { apply(cloud); cloudState = .success; cloudMessage = "已采用较新的 iCloud 数据" } else { try await CloudLedgerService.push(local); cloudState = .success; cloudMessage = "已推送较新的本地数据" } } catch { cloudState = .failed; cloudMessage = error.localizedDescription } }
    func pushToCloud() async { guard cloudSyncEnabled else { return }; cloudState = .syncing; do { try await CloudLedgerService.push(snapshot); cloudState = .success; cloudMessage = "已推送到 iCloud" } catch { cloudState = .failed; cloudMessage = error.localizedDescription } }
    func pullFromCloud() async { guard cloudSyncEnabled else { return }; cloudState = .syncing; do { if let cloud = try await CloudLedgerService.fetch() { apply(cloud); cloudState = .success; cloudMessage = "已从 iCloud 拉取" } else { cloudState = .idle; cloudMessage = "iCloud 中暂无数据" } } catch { cloudState = .failed; cloudMessage = error.localizedDescription } }
    func resolveConflict(keepLocal: Bool) async { guard let cloud = cloudConflict else { return }; if !keepLocal { apply(cloud); cloudMessage = "已采用 iCloud 版本" } else { await pushToCloud(); cloudMessage = "已保留并推送本地版本" }; cloudConflict = nil; cloudState = .success }
}
