import SwiftUI

struct TransactionsView: View {
    @EnvironmentObject private var store: LedgerStore; @State private var kind: FlowType?; @State private var dateFilter = "近30天"; @State private var categoryID: UUID?; @State private var editing: LedgerTransaction?
    private var filtered: [LedgerTransaction] { let days = dateFilter == "近7天" ? -7 : (dateFilter == "本年" ? -365 : -30); let start = Calendar.current.date(byAdding: .day, value: days, to: Date())!; return store.transactions.filter { $0.happenedAt >= start && (kind == nil || $0.kind == kind) && (categoryID == nil || $0.categoryID == categoryID) }.sorted { $0.happenedAt > $1.happenedAt } }
    var body: some View { List { Section { ScrollView(.horizontal, showsIndicators: false) { HStack { FilterButton(title: "全部", selected: kind == nil) { kind = nil }; ForEach(FlowType.allCases) { value in FilterButton(title: value.title, selected: kind == value) { kind = value } } }.padding(.vertical, 4) }; Picker("时间", selection: $dateFilter) { Text("近7天").tag("近7天"); Text("近30天").tag("近30天"); Text("本年").tag("本年") }.pickerStyle(.segmented); Menu { Button("全部分类") { categoryID = nil }; ForEach(store.categories.filter { $0.parentID == nil }) { category in Button(category.name) { categoryID = category.id } } } label: { Label(store.category(categoryID)?.name ?? "全部分类", systemImage: "line.3.horizontal.decrease.circle") } } header: { Text("筛选") }
        ForEach(grouped, id: \.0) { group in Section(group.0.formatted(date: .abbreviated, time: .omitted)) { ForEach(group.1) { transaction in TransactionRow(transaction: transaction).contentShape(Rectangle()).onTapGesture { editing = transaction }.swipeActions(edge: .trailing) { Button(role: .destructive) { store.delete(transaction) } label: { Label("删除", systemImage: "trash") }; Button { editing = transaction } label: { Label("编辑", systemImage: "pencil") }.tint(.blue) } } } }
    }.navigationTitle("流水").toolbar { ToolbarItem(placement: .topBarTrailing) { Button { editing = LedgerTransaction(title: "", amount: 0, kind: .expense) } label: { Image(systemName: "plus") } } }.sheet(item: $editing) { transaction in NavigationStack { CreateTransactionView(existing: transaction) } } }
    private var grouped: [(Date, [LedgerTransaction])] { Dictionary(grouping: filtered, by: { Calendar.current.startOfDay(for: $0.happenedAt) }).sorted { $0.key > $1.key } }
}
struct FilterButton: View { let title: String; let selected: Bool; let action: () -> Void; var body: some View { Button(action: action) { FilterChip(title: title, selected: selected) } } }
struct TransactionRow: View { @EnvironmentObject private var store: LedgerStore; let transaction: LedgerTransaction
    var body: some View { HStack(spacing: 12) { Image(systemName: store.category(transaction.categoryID)?.icon ?? "questionmark.circle.fill").frame(width: 38, height: 38).background((store.category(transaction.categoryID)?.color ?? .gray).opacity(0.15), in: Circle()).foregroundStyle(store.category(transaction.categoryID)?.color ?? .gray); VStack(alignment: .leading, spacing: 4) { Text(transaction.title.isEmpty ? "未命名流水" : transaction.title); HStack(spacing: 5) { Text(store.category(transaction.categoryID)?.name ?? "未分类"); if transaction.source == "ocr" { Text("OCR") }; if transaction.installmentMonths > 1 { Text("分期 \(transaction.installmentIndex)/\(transaction.installmentMonths)") }; if !transaction.bookIDs.isEmpty { Text("账本 ···") } }.font(.caption).foregroundStyle(.secondary); Text(transaction.happenedAt.formatted(date: .omitted, time: .shortened)).font(.caption2).foregroundStyle(.tertiary) }; Spacer(); Text((transaction.kind == .expense ? "-" : "+") + transaction.amount.currency).foregroundStyle(transaction.kind.tint).fontWeight(.semibold) } }
}
